### ISSUE TITLE
Please allow to use the externally installed kokkos package when available

### ISSUE THREAD

**Issue by yurivict** [parthenon-hpc-lab/parthenon#1168]
Currently parthenon uses the git submodule.

Parthenon installs the bundled kokkos library  which would cause conflicts with many other packages.

**Comment by pgrete** [comment]
Welcome @yurivict 

this is already possible if you set `PARTHENON_IMPORT_KOKKOS=ON`, which results in a standard `find_package(Kokkos 4)` call (instead of using the submodule).

Cheers,

Philipp

PS: Please close the issue if that solves your problem.

PPS: I'd nice if you briefly introduce yourself (see https://github.com/parthenon-hpc-lab/parthenon/issues/862) to the community as we're interested in our user base (and their needs/requirements) and how they came across Parthenon.

**Comment by yurivict** [comment]
This works.

Thank you for your advise.
