### ISSUE TITLE
Update to Kokkos 4.2?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#1190]
On HIP machines, we're using `Kokkos::printf` which was added to Kokkos 4.2. Any chance we can bump the version number of Kokkos?

**Comment by pgrete** [comment]
~Parthenon is on Kokkos 4.4.1 since last week (that rogue merge that directly ended up on `develop` due to missing branch protection rules), https://github.com/parthenon-hpc-lab/parthenon/commit/a9b78586f025f25c706fd3d06efd306e6052a7e9
Or am I missing sth?~

Oh wow... sth really went wrong there... I apparently did not update the submodule.
Do you mind adjusting #1191 to 4.4.1 and update the existing changelog?
