### ISSUE TITLE
Shared pointer reference counting 

### ISSUE THREAD

**Issue by brryan** [parthenon-hpc-lab/parthenon#316]
@JoshuaSBrown raised an issue with passing shared pointers as references, e.g. `Real EstimateTimestep(std::shared_ptr<Container<Real>> &rc)`, in #126. This is going to be a broader change than what's in that PR so I'm creating an issue instead.

**Comment by AndrewGaspar** [comment]
Our code is definitely addicted to passing around `shared_ptr`s when they aren't needed. Indeed, I actually think it's harmful because the look of it to the consumer is to say "hey, go ahead and take a reference to this shared_ptr, no problem!", when in fact, I don't think that taking a reference on the shared_ptr to the `Container` is all that helpful, since it doesn't own a reference to the underlying `MeshBlock` anyway. If you hold onto the `Container` past the lifetime of the `MeshBlock`, the `MeshBlock` is dropped, but the `Container` lives on.

**Comment by pgrete** [comment]
It'd be great if we could address this with the upcoming change in interface we discussed on Tuesday, @jdolence 
Likely you already discussed that at a different place (I can't find it right away), but it'd be great to have some kind of general style guide for passing around argument, e.g, const refs for immutable objects and raw pointers for object that should change.

**Comment by Yurlungur** [comment]
Code style is now to pass raw pointers, owned by smart pointers, e.g., `foo(bar.get());`

**Comment by pgrete** [comment]
ping @pgrete review
