### ISSUE TITLE
Semantics of useing interior and exterior to define boundaries

### ISSUE THREAD

**Issue by JoshuaSBrown** [parthenon-hpc-lab/parthenon#354]
I find the use of interior and exterior to define boundaries confusing, I would propose to change these were appropriate to something more along the lines of front/back, anterior/posterior, fore/aft. Particularly when talking with regard to ghost zones describing the interior of a meshblock makes me think we are referring to the meshblock without the ghost zones, not as it is being used to describe the ghost zone on one side of the mesh block.

**Comment by Yurlungur** [comment]
This discussion came from #332 . 

I am fine with making this change, but only after some discussion, because these names show up everywhere. There may also be some desire to keep the same names for continuity with Athena++. @jmstone and @pgrete may be able to comment.

Of your suggestions, @JoshuaSBrown I think I like fore/aft best.

**Comment by Yurlungur** [comment]
It's worth pointing out that `inner/outer` is not far from standard parlance for numerical simulations. People often talk about inner and outer boundary conditions to refer to, e.g., the inner radius and outer radius of a spherical shell.

**Comment by jdolence** [comment]
`inner` and `outer` might be a little confusing.  I've always preferred `low` and `high` or `lo` and `hi`.  Not sure what the implications might be, so I agree we should hear from others before changing this.
