### ISSUE TITLE
Add MPI Communication Tagging Bounds Checking

### ISSUE THREAD

**Issue by AndrewGaspar** [parthenon-hpc-lab/parthenon#448]
We just got bit by this issue with the "advection_performance" test running on 4 ranks (yeah, I know, we're not supposed to do that) on Trinitite using cray-mpich: https://github.com/lanl/SNAP/issues/6

Our current communication tags are structured as:
```
32|----block ID----|11|----buffer ID----|5|----phsyics ID----|0
```

So 5 bits (range [0,31]) for physics ID, 6 bits (range [0,63]) for buffer ID, and 21 bits (range [0,2097151]) for the block ID. So we should have room in our tag for over 2 million blocks per rank, which seems reasonable enough, right?

Unfortunately, cray-mpich limits us, based on our current tag logic, where the block ID is padded out 11 bits, to no more than 2^10 (1024) blocks per rank.

There are a few places in the code that are missing what would be valuable bounds checking for MPI communication tagging.

Check that "Physics ID"s (when multi-rank) don't exceed 2^5-1:
https://github.com/lanl/parthenon/blob/4495e6cf2d1c25308c58ee719a7a05247aad4af8/src/bvals/bvals.cpp#L141

Check that the total tag ID doesn't exceed MPI_TAG_UB (though hopefully unnecessary with other changes).
https://github.com/lanl/parthenon/blob/b6b8e0d3dd61f649e48253d2adb93dc5cd76b555/src/bvals/bvals_base.cpp#L289

Check that block ID (for multi-rank runs) doesn't exceed `MPI_TAG_UB >> 11`:
https://github.com/lanl/parthenon/blob/b6b8e0d3dd61f649e48253d2adb93dc5cd76b555/src/mesh/meshblock.cpp#L79

I don't fully understand how any of this works with `BoundaryBase::CreateBufferID`, since it's calculation seems to guarantee a value with more than 6 bits:
https://github.com/lanl/parthenon/blob/b6b8e0d3dd61f649e48253d2adb93dc5cd76b555/src/bvals/bvals_base.cpp#L126

**Comment by pgrete** [comment]
Interesting, that could explain the issue that @JoshuaSBrown saw (#384), doesn't it?
I'm currently also hitting a tag issue with Intel MPI 19 and vanilla Athena++, which also seems to be linked to the lower number of tags supported.
Pinging @jmstone for reference.

**Comment by pgrete** [comment]
One more point. The block ids are the global ids, aren't they? So it's a 2 million block total limit (ideally) and 1024 (on cray) and not a per rank limit.
This would make this way more serious.

**Comment by jmstone** [comment]
MPI tags are constructed from local IDs, so the limit is per rank, not total for the job.  Not sure how to get around this except to use different communicators for different physics, as Philipp suggested.  Since communication of different buffers with different variables (physics) occurs simultaneously, then you have to have someway to create unique tags.

**Comment by pgrete** [comment]
Right, local ids, I missed that the point-to-point communication between ranks is guaranteed to be unique using local ids.
I don't expect we'll have 32k+ blocks per node anytime soon, so separating the physics could be a safe option for now.

So it seems that the issue I mentioned above  is not related to the tags used for buffers, but only for MPI IO (where somewhere down in the callstack the logic uses large tag ids: `PMPI_Issend(156): MPI_Issend(buf=0x2b96166114b4, count=1048576, MPI_BYTE, dest=0, tag=1058504, comm=0x84000002, request=0x7f200004f2c0) failed
PMPI_Issend(95).: Invalid tag, value is 1058504`. Just mentioning it here so that more people have that in their minds.

**Comment by jmstone** [comment]
MPI tags are constructed from local IDs, so the limit is per rank, not total for the job.  Not sure how to get around this except to use different communicators for different physics, as Philipp suggested.  Since communication of different buffers with different variables (physics) occurs simultaneously, then you have to have someway to create unique tags.

**Comment by jmstone** [comment]
Yes, the problem with MPI-IO has also been encountered with other groups running Athena++ on Frontera.  However, Athena++ does not create tags for MPI-IO, as there are no explicit sends or receives.  This is some internal tag being created in the MPI-IO library.  So I really don't know how to fix that.

**Comment by Yurlungur** [comment]
Resolved
