### ISSUE TITLE
`RestrictPhysicalBounds` in driver with `MeshData` still required?

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#626]
In the advection example, we call the `RestrictPhysicalBounds` task also for the `MeshData` version:
https://github.com/lanl/parthenon/blob/05e2f5be2a8789ceae9fdbbb565c55f804f55da4/example/advection/advection_driver.cpp#L181

Is this still required or a leftover from when restrict was not handled yet by the cell centered machinery, see, e.g.,  https://github.com/lanl/parthenon/blob/05e2f5be2a8789ceae9fdbbb565c55f804f55da4/src/bvals/cc/bvals_cc_in_one.cpp#L273

Ping @Yurlungur @jdolence

**Comment by pgrete** [comment]
Any quick comment on the question above? @Yurlungur @jdolence

**Comment by Yurlungur** [comment]
Sorry for the delay @pgrete . I was sick last week. I will double check this now.

**Comment by Yurlungur** [comment]
Ah ok. I do not believe this code can go away. If I recall, restriction has always handled restriction for communication. This always simply restricts for communication to a neighbor block. However, that's not all that's required for restriction. The physical boundary conditions must also be set on the coarse buffer. But these aren't set by the communication routines. 

It's possible this could be unified with the other boundary machinery and cleaned up. (And it's also possible I don't fully understand something... It's been a while since I looked at this.) But that's my recollection.
