### ISSUE TITLE
User bounds force swarm bounds

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#675]
When using user boundary function, swarm boundary function are currently enforced in Parthenon at the mesh level, e.g., 
```c++
    switch (mesh_bcs[f]) {
    case BoundaryFlag::user:
      if (app_in->swarm_boundary_conditions[f] != nullptr) {
        SwarmBndryFnctn[f] = app_in->swarm_boundary_conditions[f];
      } else {
        std::stringstream msg;
        msg << "A user boundary condition for face " << f
            << " was requested, but no swarm condition was enrolled." << std::endl;
        PARTHENON_THROW(msg);
      }
      break;
    default: // Default BCs handled elsewhere
      break;
    }
```

If a downstream app/package does not make use of particles, this results in a hard fail nevertheless.

I wonder what the best solution would be, i.e., where the error handling/sanity should happen?
At the downstream code? In Parthenon (e.g., when a package enrolls particles)? Should we only have one "user function/struct" that contains both so that we implicit enforce "users" to be conscious about both types of functions?
Any thoughts? @Yurlungur @brryan

**Comment by brryan** [comment]
Yes I see this now in our downstream code when `user` boundaries are requested but only field boundaries are provided, even if there is no swarm. Sorry! I think this is an easy fix actually, since we do already also check for swarm boundaries being non-`nullptr` in `Swarm::AllocateBoundaries()`. So we can just remove the check you highlighted and everything seems to work correctly on my end. PR is up.
