### ISSUE TITLE
Store arbitrary/mesh data in output

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#683]
Do we have a way to store (and restore) arbitrary data (e.g., not tied to a block) in our output files apart from abusing the "input file"?
Specifically, I need to save a (small) array of complex numbers that is identical across all ranks and blocks.

**Comment by Yurlungur** [comment]
I don't think so---this is something I think we'd be interested in having too. It would be useful to be able to save, e.g., `Kokkos::View`s stored in `param`s. Maybe if we had some serialization mechanism?

**Comment by pgrete** [comment]
I also thought about the `Params`. If I didn't miss anything then we currently don't read/restore `Params` from the restart file.
From my point of view, this sounds reasonable and should probably stay that way because it prevents a misalignment between the input file and the `Params` object. In other words, the "active" `Params` always relies on being (re)populated in a consistent manner during package initialization.
Do you agree?

If yes, then I could imagine to introduce a function at the `Mesh` level to register objects that contain a `.data()` and a `.size()` function with an optional (`Metadata::Restart` flag) to a) create non-global (in the c++sense) `Mesh` data [1] (but not `MeshData`) and b) store/restore for outputs.
Potentially, the existing container layout could be repurposed for this.
Any thoughts? also ping @brryan @lroberts36 @jdolence 

[1] I'm currently creating my "global" `ParArrays` in a pgen namespace. While this works (but also requires manual cleanup as they are, by default, not deallocated before `Kokkos::finalize` is called), I think it would be cleaner to tie this kind of data to the `Mesh` itself.

**Comment by Yurlungur** [comment]
> If I didn't miss anything then we currently don't read/restore Params from the restart file.

Ah, that's possible. I know we output `Params`, but I think you may be right that we don't read from them. I'm also pretty sure this mechanism fails for `Kokkos::View`. 

> From my point of view, this sounds reasonable and should probably stay that way because it prevents a misalignment between the input file and the Params object. In other words, the "active" Params always relies on being (re)populated in a consistent manner during package initialization.
> Do you agree?

I don't think it should matter in principle, but you're right that we currently set them in `Initialize` every setup, so reading them again from the restart file is currently not consistent. We'd need some mechanism for preventing them for being reset by `Initialize` when we restart.

> If yes, then I could imagine to introduce a function at the Mesh level to register objects that contain a .data() and a .size() function with an optional (Metadata::Restart flag) to a) create non-global (in the c++sense) Mesh data [1] (but not MeshData) and b) store/restore for outputs.
> Potentially, the existing container layout could be repurposed for this.

I wouldn't be opposed to this---it seems reasonable. And in fact, I believe I wrote such a thing earlier in Parthenon's life, but all the bits rotted because we decided we didn't need it at the time. ;)

We could perhaps leverage all the machinery we currently have---maybe we register mesh-level variables that are owned per rank and don't have a default shape? I bet that wouldn't be too hard to do.

**Comment by Yurlungur** [comment]
I decided to go ahead and write a version that abuses `Params`, rather than a `Mesh` level data type. Curious what you think @pgrete . Consistency is contractually enforced by setting what is read from the restart file vs initialized by a package.
