### ISSUE TITLE
Move prolongation/restriction and buffer info machinery to own directories

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#704]
@lroberts36 points out that it would be nice to re-organize the code to move the buffer logic and prolongation/restriction logic into its own directory higher up in the source tree. The suggested time to do this is in a reorganization step after sparse is merged in. I agree and think when we thread prolongation/restriction into userland, that might be a good opportunity.

**Comment by lroberts36** [comment]
Things we might want to do as part of the cleanup: 
- Rename `cc/sparse_bvals_in_one.cpp` and `cc/sparse_flux_correction_in_one.cpp` and move everything out of `cc/` directory since we likely want to unify boundary communication for different types of variables. 
- Move `BndInfo` object to its own file from `cc/bvals_in_one.hpp`, since it is used in a few different places in the code. `calc_indices.cpp` should probably be changed to `bnd_info.cpp`. Maybe rename `BndInfo` since it actually contains the info for loading a 1D buffer from a sub-domain of a 3D array (which doesn't necessarily correspond to a boundary)?
- Remove any dead code we can from the `bvals` directory (for instance is the `fc` stuff used at all?)
- Move prolongation and restriction to their own directory. Cleanup possibly unused code like `RestrictField*`? Move `mesh/mesh_refinement_ops.hpp` and `refinement_cc_in_one.*` to something that makes it more clear these contain the prolongation and restriction routines (which are not only used during refinement).

**Comment by Yurlungur** [comment]
I'm in favor of all of this. But I would argue we should keep `RestrictField*` in place until @forrestglines has finished with the face stuff, as that code may be a useful reference.

**Comment by lroberts36** [comment]
Yes, keeping that in makes sense. Could always move to a `dead_code` folder if we wanted to keep it around for a while but do the cleanup sooner than later.

**Comment by lroberts36** [comment]
At this point, I think that all of the cleanup suggestions in this comment have been implemented in `develop`.
