### ISSUE TITLE
Developer Meeting questions/issues

### ISSUE THREAD

**Issue by jdolence** [parthenon-hpc-lab/parthenon#727]
This issue is to keep track of questions, issues, problems, etc. that come up as people pick of Parthenon for the first time and try to come up to speed before the Developer Meeting.

Please post any issues you think should be addressed or you'd like discussed at the Developer Meeting.

**Comment by pdmullen** [comment]
Getting excited for the workshop! 😄 A few notes from my first experiences with Parthenon and things I'd like to see discussed:

(1) To get up-and-running on my Mac (with HDF5), I had to make the changes in PR #613.
(2) The Wiki is a bit hard to navigate.  When I navigate to the Wiki tab, I see links to meeting notes (which are exciting to read through; thanks for including these!) and corresponding pages on the right hand side.  But it is difficult to navigate to operational Parthenon content.  Maybe the plan is to keep all documentation in `docs/` and reserve the Wiki for development notes?
(3) The `TaskList` infrastructure and the granularity it supports is really neat.  In general, I'd like a brief discussion about the `TaskList` and how people have exploited the infrastructure for their physics applications.  When the Parthenon dev team was designing the `TaskList`, I am sure they had physics inspired motivations---what were those? What common tasks do you see belonging to different types of `TaskRegion`s?  If I had a calculation that was invoking (a) hydro evolution, (b) radiation, and (c) field evolution, for example...is the Parthenon meta to create a `TaskList` for each, whereby one interweaves between said `TaskList`s...or should one create a master `TaskList` to rule them all? 
(4) One major change between Parthenon and Athena++ (and AthenaK and Athena++ for that matter) is the prolongation and restriction of conserved variables (vs primitive variables).  How are peoples' experience with that? Anybody have experience with this in a GR context?  Can these operations take us to a state where C2P fails whereby operating with primitive variables would not?
(5) What is the status of face-centered fields? For field evolution, will Parthenon communicate EMF's at same level boundaries? Also, I recently brought up this issue in the Athena++ repo: https://github.com/PrincetonUniversity/athena/discussions/455.  Does anyone share this concern?
(6) Anybody working on asynchronous I/O? This would be super cool.
(7) Athena++ just released a multigrid solver (https://github.com/PrincetonUniversity/athena/tree/multigrid) ...any plans to port to Parthenon?

**Comment by pgrete** [comment]
Wish list/feature requests (in any order)

- `AnalysisDriver`
- In-situ analysis
- IO
  - Performance
    - may be slow(?)/could be further optimized
    - use separate host thread
  - Need more flexible output shapes
  - Need support for particle IO
  - Support for lossy data compression
- Face-, edge- and node-centered vars
  - needed for MHD
  - also good for dynamical spacetimes
  - possible options
    - separate vars (as in Athena++)
    - promote CellCenteredVar to Vars and create FaceCenteredField based on slightly larger allocations <- currently favored
    - make FaceCentered, three CellCentered
- Physical boundaries
  - currently does not support `MeshData` yet
  - also more fine grained boundary function (e.g., per `Package`)
- Tagging cells for refinement
  - also no support for `MeshData` at the moment
- Prolongation/restriction
  - Likely need to allow for primitive prolongations
- Communicate buffers
  - based more fine-grained selection (instead of `WithFluxes`)
  - combine buffers for same-rank comm
  - use simple address to address copy instead of `k,j,i`
- Support for higher order methods
- Particles
- Load balancing (similar to Athena++ with block local cost)
  -  current infrastructure is good for uniform (per block) loads, but that does not apply when additional physics are involved such as sparse or variable inversion
  - with `MeshBlockPack`s the original infrastructure is not directly applicable any more
  - quick first thoughts
    - based on mem usage
    - rank based timing
    - use "global view" of running sim
    - provide hooks for (downstream) cost estimates
- Add more `EstimateTimestep` callback functions
- Code cleanup
  - lots of leftover/half-dead/dead code that could be removed, such as `bvals`
  - we should probably only support one code path (i.e., remove `MeshBlockData` code paths and only support `MeshData`)
  - Unify sparse and dense packs
  - Cleanup `interface`directory (i.e., less "code" in there)
- `par_for_inner` improvements
  - translate to some work size (for easier vectorization)
  - potentially automate pulling out pointer (again for vectorization) 
- `FluxCorrection`-in-one
- Use object pools for `CellVariable` `ParArrays` to minimize allocation during remesh (similar to comm buffers)
- Multi-threaded task lists (so that there can be a separate thread handling the `MPI_IRecv`s)
- Cleanup/fix reductions across multiple blocks
- Reduce sparse MPI comm during `RedistributeAndRefineMeshblocks`
- Check that single precision works (and make sure that any global reductions are at higher precision)
- Support running in mixed-precision
  - e.g., to accelerate simulations (run at lower prec until certain threshold and then promote)
  - safe on memory
- (Similarly) support integer or enum type for `Variables` 
- `FluxDiv` for subset of variables
- Provide "auto-tuning" framework
  - to optimize for pack_size, ranks per GPU, buffer memory space, loop pattern, etc.
- Support for higher order methods
  - what changes to we need in Parthenon?
- Support for linear solvers?
  - Get CG and BiCGStab to `develop`
  - Port Multigrid from Athena++
  - Interface to other libs? 
- Additional discussions 
  - first order flux correction
  - DG methods
- Extension of the time integrator
  - Support ImEx? Spectral deferred correction?
  - RKL2 STS
  - Branding
    - Can we move to sth like a GitHub collaboration that hosts more project including parthenon-hydro, AthenaPK
- Documentation
  - need more doc, especially for new users, i.e., "get started/intro" tutorial
  - move to more modern infrastructure and publish to readthedocs

**Comment by Yurlungur** [comment]
Meeting was a success. See other issues!
