### ISSUE TITLE
Archival parameter dumps

### ISSUE THREAD

**Issue by c-prather** [parthenon-hpc-lab/parthenon#754]
There was a request for outputting a set of all Parthenon's parameters -- this is offered for downstream codes to do, but would be useful as an optional upstream feature.  For example, in KHARMA:

```c++
    // We could still have set parameters during driver initialization
    // Note the order here is *extremely important* as the first statement has a
    // side effect which must occur on all MPI ranks
    if(pin->GetOrAddBoolean("debug", "archive_parameters", false) && MPIRank0()) {
        // Write *all* parameters to a parfile for posterity
        std::ostringstream ss;
        auto itt_now = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
        ss << "kharma_parsed_parameters_" << std::put_time(std::gmtime(&itt_now), "%FT%TZ") << ".par";
        std::fstream pars;
        pars.open(ss.str(), std::fstream::out | std::fstream::trunc);
        pin->ParameterDump(pars);
        pars.close();
    }
```

This seems easy to push upstream but I'm not sure what options should be called, where this fits, etc.  Would be edifying for me to learn/see from a core dev where it should end up.

**Comment by tagardiner** [comment]
@jonahm-LANL @bprather I'd be happy to take this on as an option to add to parthenon as it will help me work through how this code starts up and begins execution.  Some simple questions:

Presumably you'd like this to be optional, hence there's a default behavior.  I'd recommend that the default behavior is to have it turned on.

In my work, I always have this on and it simply dumps to a file named "sim_rerun.in".  This is sufficient because I typically run a calculation like this

<exec> -i input_file -d run_dir <command line arguments> &

This way, the input file is loaded and updated with command line arguments, a directory made and changed into, and then in that directory the updated parameter file (with defaults and command line changes) is written to sim_rerun.in.  So there's always a run directory with output files and an input file to recreate it.

Is this a sufficient default, or should time-stamping be the default?

What block should the controlling parameter be added to? <parthenon/job>

Parameter name & value? 
write_input = {no, yes, time_stamped, ...}

where no is obviously no, 
yes => "parthenon_rerun.in"
time_stamped => "parthenon_2022-10-07T20\:25\:02Z.in"

or something like that.

BTW, does parthenon use the suffix ".in" like "input_file_name.in" or "input_file_name.par"?

**Comment by c-prather** [comment]
I have a PR open that tries to implement the basics of this, #755, but I'm not sure it's what anyone else wants and I'd welcome any input.  I stuck with a very basic "generate parthinput.archive when parthenon/job/archive_parameters is true," with an additional option "archive_parameters_timestamp" to add a timestamp.

It looks like the PR is stuck on the formatter's dislike of std::chrono for generating the timestamp.

**Comment by Yurlungur** [comment]
> It looks like the PR is stuck on the formatter's dislike of std::chrono for generating the timestamp.

The `std::chrono` thing is a function of `cpplint` which has some google-specific [idiosyncrasies](https://stackoverflow.com/questions/33653326/google-style-guide-chrono-is-an-unapproved-c11-header).

>  I stuck with a very basic "generate parthinput.archive when parthenon/job/archive_parameters is true," with an additional option "archive_parameters_timestamp" to add a timestamp.

This seems fine to me.

> BTW, does parthenon use the suffix ".in" like "input_file_name.in" or "input_file_name.par"?

We actually either use `parthinput.*` or `*.pin`

**Comment by Yurlungur** [comment]
> What block should the controlling parameter be added to? <parthenon/job>

`parthenon/job` seems perfectly reasonable to me.

**Comment by c-prather** [comment]
Closing with merge of #755
