### ISSUE TITLE
Does anyone use `ParthenonInit`

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#929]
For historical reasons, we have two ways of setting up Parthenon's runtime:
1. First call `ParthenonInitEnv` and then call` ParthenonInitPackagesAndMesh`. The former sets up MPI and Kokkos, and reads in the command line arguments and input deck. The latter calls all the `Initilalize` function for all packages and calls the mesh constructor.
2. `ParthenonInit` simply calls `ParthenonInitEnv` and `ParthenonInitPackagesAndMesh` one after the other.

It's easy to confuse `ParthenonInit` and `ParthenonInitPackagesAndMesh` by writing code like:
```C++
ParthenonManager pman;
pman.ParthenonInit(argc, argv);

// do some code, set app inputs

pman.ParthenonInitPackagesAndMesh();
```
where the intended code was actually

```C++
ParthenonManager pman;
pman.ParthenonInitEnv(argc, argv);

// do some code, set app inputs

pman.ParthenonInitPackagesAndMesh();
```

This seems error prone. Does anyone actually use the older, unified `ParthenonInit` function? If not, perhaps we should just remove it. 

Alternatively, we could add error checking so that if any of the `ParthenonInit*` functions is called twice by the same manager object, an error is raised.

**Comment by Yurlungur** [comment]
Ping @jdolence @lroberts36 @bprather @pgrete

**Comment by c-prather** [comment]
I think I was vaguely aware Init was being split, but I never switched to the new calls.  I should have, because I effectively call things in between and this makes that cleaner.  I'll switch today.

I'm in favor of deprecating/removing unified init (after I'm done please), and independently also of throwing errors or very strong warnings when calling the new `Init` functions again.  I think there may be use cases for initializing more than one mesh per run though, can we split that out from the packages?

EDIT one could always just make a new manager object.  But that re-initializes MPI and probably leads to issues

**Comment by lroberts36** [comment]
Based on my experience this afternoon, I am strongly disposed towards removing `ParthenonInit` entirely. I think that adding error checking wouldn't have solved (the admittedly stupid) issue I was beating my head against.

Really, I think my issue was due to blindly copying code from another example and then adding some code below that without thinking. This does seem like an issue a new user could easily run into though.

**Comment by Yurlungur** [comment]
PR #930
